stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
      - data/data.csv
    outs:
      - data/processed

  transform:
    cmd: python src/transform.py
    deps:
      - src/transform.py
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - data/transformed

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/transformed/X_train.csv
      - data/transformed/y_train.csv
    outs:
      - models

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models
      - data/transformed/X_test.csv
      - data/transformed/y_test.csv
    outs:
      - metrics.json